### ISSUE TITLE
bigpipe ppt好像下载不了

### ISSUE THREAD

**Issue by Arlenmbx** [owenliang/bigpipe#15]
Can you hava a check? @owenliang

**Comment by owenliang** [comment]
@Arlenmbx shadowsocks全局模式试一下，一般是被墙了。

**Comment by Arlenmbx** [comment]
@owenliang hi,我们可以加个微信，我想有些问题咨询你一下？

**Comment by Arlenmbx** [comment]
你的不需要在本地额外配置zookeeper和kafka吗？只需要配置librdkafka就可以吗？
